name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  buildAndDeploy:
        # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      contents: read
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js and npm
      uses: actions/setup-node@v2.5.2

    - name: Install dependencies and grunt-cli
      run: |
        npm install

    - name: Build
      run: grunt

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v2
      with:
        timeout: 60000
        artifact_name: dist/public
