name: Build and Deploy

on:
  push:
    branches:
      - main

permissions:
    contents: write
    pages: write
jobs:
  buildAndDeploy:
        # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js and npm
      uses: actions/setup-node@v2.5.2

    - name: Install dependencies and grunt-cli
      run: |
        npm install

    - name: Build
      run: grunt

    - name: list directories 
      run: |
        ls -R

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: dist
        branch: gh-pages

